Portal/MiniCrm.Web/Controllers/CustomerController.cs
using EnzoMiniCrm.Model;
using log4net;
using Mechanik.Repository;
using MiniCrm.Web.Models;
using PetaPoco;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MiniCrm.Web.Controllers
{

    public class CustomerController : Controller
    {
        protected string _message = "Wystąpił problem z Twoim rządaniem, skontaktuj się z administratorem";

        protected static readonly ILog _log = LogManager.GetLogger("CustomerController");
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Customer()
        {
            ViewBag.Message = "Your Page to manage customers.";

            return View();
        }
        public JsonResult ShowCustomerList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            int totalRecords;
            using (var db = new Database("DefaultConnection"))
            {
                try
                {
                    var sql = PetaPoco.Sql.Builder.Append("Select * from dbo.Customers ");
                    totalRecords = (db.Query<Customer>(sql)).Count();
                    
                    sql.Append("ORDER BY CustomerID OFFSET @0 ROWS FETCH NEXT @1 ROWS ONLY", jtStartIndex, jtPageSize);
                    var result = db.Query<Customer>(sql);
                    
                    return Json(new { Result = "OK", Records = result, TotalRecordCount = totalRecords });


                }
                catch (Exception ex)
                {
                    _log.Error(ex);
                    return Json(new { Result = "ERROR", Message = _message });
                     
                }
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, employee")]
        public JsonResult GetCustomerID()
        {
            try
            {
                using (var db = new Database("DefaultConnection"))
                {
                    var result = db.Fetch<Customer>("Select * from Customers").Select(c => new { DisplayText = c.CustomerID, Value = c.CustomerID });
                    return Json(new { Result = "OK", Options = result });
                }
            }
            catch (Exception ex)
            {
                _log.Error(ex);
                return Json(new { Result = "ERROR", Message = _message });
            }
        }
        [HttpPost]
        public JsonResult NewGetCustomerID()
        {
            try
            {

                var result = new CustomerRepository(new Database("DefaultConnection")).GetById("tyborrafal@gmail.com");
                    return Json(new { Result = "OK", Options = result });
     
            }
            catch (Exception ex)
            {
                _log.Error(ex);
                return Json(new { Result = "ERROR", Message = _message });
            }
        }
    }
}

Portal/MiniCrm.Web/Controllers/MailingController.cs
using ActiveUp.Net.Mail;
using EnzoMiniCrm.Model;
using log4net;
using PetaPoco;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Mail;
using System.Net.Mime;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace MiniCrm.Web.Controllers
{
    public class MailingController : Controller
    {
        protected string _message = "Wystąpił problem z Twoim rządaniem, skontaktuj się z administratorem";
        protected static readonly ILog _log = LogManager.GetLogger("Controller");
        // GET: Mailing
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Mailing()
        {

            return View();
        }
        public ActionResult GetSendMailList()
        {

            return View();
        }


        [HttpPost]
        public JsonResult ShowMailingList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            int TotalRecordCount;
            using (var db = new Database("DefaultConnection"))
            {
                try
                {
                    var totalRecords = db.Fetch<Mail>("Select * from dbo.Mails");
                    var result = db.Fetch<Mail>("Select * from dbo.Mails ORDER BY MailID OFFSET @0 ROWS FETCH NEXT @1 ROWS ONLY", jtStartIndex, jtPageSize);
                    TotalRecordCount = result.Count;
                    return Json(new { Result = "OK", Records = result, TotalRecordCount = totalRecords.Count });
                }
                catch (Exception ex)
                {
                    return Json(new { Result = "ERROR", Message = ex.Message});
                    //TODO add log4net_log.Error(ex.ToString());

                    throw;
                }
            }
        }
        [HttpPost]
        public JsonResult CreateMail(Mail mail)
        {
            try
            {     
                using (var db = new Database("DefaultConnection"))
                {
                    db.Insert(mail);
                    SendEmail(mail);
                    return Json(new { Result = "OK", Record = mail });
                }
                
            }
            catch (Exception ex)
            {
                _log.Error(ex);
                return Json(new { Result = "ERROR", Message = _message });
            }
        }
        public JsonResult MailingGetById(int mailID)
        {
            try
            {
                using (var db = new Database("DefaultConnection"))
                {
                    var result = db.Fetch<Mail>("Select * from dbo.Mails where MailId = @0", mailID);
                    return Json(new { Result = "OK", Records = result });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult GetReciveMailList()
        {
            List<Mail> result = new List<Mail>();
            try
            {
                var mailRepository = new MiniCrm.Web.Helpers.MailRepositorycs.MailRepository(
                            "imap.gmail.com",
                            993,
                            true,
                            "enzoitsollutions@gmail.com",
                            "EnzoAdmin123@1"
                        );

                var emailList = mailRepository.GetAllMails("inbox");
                int i=1;
                foreach (Message email in emailList)
                {
                    result.Add(new Mail { From = email.From.Email, Subject=email.Subject, Body = email.BodyText.TextStripped, MailID = i, SendingDate = email.Date });
                        i++;
                    if (email.Attachments.Count > 0)
                    {
                        foreach (MimePart attachment in email.Attachments)
                        {
                            
                        }
                        
                    }
                }
                return Json(new { Result = "OK", Records = result });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        public JsonResult GetUnreadeMailList()
        {
            List<Mail> result = new List<Mail>();
            try
            {
                var mailRepository = new MiniCrm.Web.Helpers.MailRepositorycs.MailRepository(
                            "imap.gmail.com",
                            993,
                            true,
                            "enzoitsollutions@gmail.com",
                            "EnzoAdmin123@1"
                        );

                var emailList = mailRepository.GetAllMails("unseen");
                int i = 1;
                foreach (Message email in emailList)
                {
                    result.Add(new Mail { From = email.From.Email, Subject = email.Subject, Body = email.BodyText.TextStripped, MailID = i, SendingDate = email.Date });
                    i++;
                    if (email.Attachments.Count > 0)
                    {
                        foreach (MimePart attachment in email.Attachments)
                        {

                        }

                    }
                }
                return Json(new { Result = "OK", Records = result });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        public JsonResult DeleteMailById()
        {
            try
            {
          
                using (var db = new Database("DefaultConnection"))
                {
                    db.Delete("Mails", "MailID", null);
                    return Json(new { Result = "OK" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        [HttpPost]
        [Authorize(Roles="admin, employee")]
         private void SendEmail(Mail mail)
        {
           
            // For information on sending mail, please visit http://go.microsoft.com/fwlink/?LinkID=320771
            try
            {
            #region formatter
            string text = string.Format("Please click on this link to {0}: {1}", mail.Body, mail.Body);
            string html = "" + mail.Body;

            //html += HttpUtility.HtmlEncode(@"Or click on the copy the following link on the browser:" + message);
            #endregion

           
            MailMessage msg = new MailMessage();
            msg.From = new MailAddress("enzoitsollutions@gmail.com");
            msg.To.Add(new MailAddress(mail.CustomerID));
            msg.Subject = mail.Subject;
            msg.AlternateViews.Add(AlternateView.CreateAlternateViewFromString(text, null, MediaTypeNames.Text.Plain));
            msg.AlternateViews.Add(AlternateView.CreateAlternateViewFromString(html, null, MediaTypeNames.Text.Html));

            System.Net.Mail.SmtpClient smtpClient = new System.Net.Mail.SmtpClient("smtp.gmail.com", Convert.ToInt32(587));
            System.Net.NetworkCredential credentials = new System.Net.NetworkCredential("enzoitsollutions@gmail.com", "EnzoAdmin123@1");
            smtpClient.Port = 587;
            smtpClient.Credentials = credentials;
            smtpClient.EnableSsl = true;
            smtpClient.Send(msg);
            mail.ErrorRaport = "OK";
                //Update the record mail
            
                

            }
            catch (Exception ex)
            {
                _log.Error(ex);
                mail.ErrorRaport = ex.Message;
                
            }
            finally
            {
                mail.SendingDate = DateTime.UtcNow;
                using(var db = new Database("DefaultConnection"))
                {
                    db.Update(mail);

                }
              
            }
     
        }
    }
}

Portal/MiniCrm.Web/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniCrm.Web.Controllers
{
    public class OfferController : Controller
    {
        // GET: Offer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OfferList()
        {
            return View();
        }
    }
}

Portal/MiniCrm.Web/Controllers/RepairController.cs
using EnzoMiniCrm.Model;
using log4net;
using Mechanic.BL.Constans;
using PetaPoco;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniCrm.Web.Controllers
{
    public class RepairController : Controller
    {
        protected string _message = "Wystąpił problem z Twoim rządaniem, skontaktuj się z administratorem";
        protected static readonly ILog _log = LogManager.GetLogger("Controller");
        private DictionaryStatusesRepair dictionaryStatusesRepair = new DictionaryStatusesRepair();

        // GET: Rapair
        public ActionResult Index()
        {
            return View();
        }

   
        public ActionResult Repair()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin, employee")]
        public JsonResult ShowRepairList(int StatusId = 0, int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            int totalRecords;
            using (var db = new Database("DefaultConnection"))
            {
                try
                {
                   
                    var sql = PetaPoco.Sql.Builder.Append("Select * from dbo.Repairs ");
                    totalRecords = (db.Query<Mail>(sql)).Count();

                    if (dictionaryStatusesRepair.HasKey(StatusId))
                    {
                        sql.Append("Where Status = @0", StatusId);
                    }
                    sql.Append(" ORDER BY RepairID OFFSET @0 ROWS FETCH NEXT @1 ROWS ONLY", jtStartIndex, jtPageSize);
                    var result = db.Query<Repair>(sql);
                    return Json(new { Result = "OK", Records = result, TotalRecordCount = result.Count() });
                }
                catch (Exception ex)
                {
                    _log.Error(ex);
                    return Json(new { Result = "ERROR", Message = _message });
                }
            }
        }
        [HttpPost]
        [Authorize(Roles = "admin, employee")]
        public JsonResult CreateRepair(Repair repair)
        {
            try
            {
                using (var db = new Database("DefaultConnection"))
                {
                    db.Insert(repair);
                    return Json(new { Result = "OK", Record = repair });
                }
            }
            catch (Exception ex)
            {
                _log.Error(ex);
                return Json(new { Result = "ERROR", Message = _message });
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, employee")]
        public JsonResult GetEmployeeID()
        {
            try
            {
                using (var db = new Database("DefaultConnection"))
                {
                    var result = db.Fetch<Employee>("Select * from Employees").Select(c => new { DisplayText = c.EmployeeID, Value = c.EmployeeID });
                    return Json(new { Result = "OK", Options = result });
                }
            }
            catch (Exception ex)
            {
                _log.Error(ex);
                return Json(new { Result = "ERROR", Message = _message });
            }
        }
        [HttpPost]
        [Authorize(Roles = "admin, employee")]
        public JsonResult DeleteRepair(string RepairID)
        {
            try
            {

                using (var db = new Database("DefaultConnection"))
                {

                    using (var scope = db.GetTransaction())
                    {
                       
                        //search and delete repair
                        Repair repair = db.Single<Repair>("Select * from Repairs where RepairID = @0", RepairID);
                        db.Delete(repair);


                        //search and delete all status from before deleteing repair
                        var statuses = db.Fetch<RepairsStatus>("Select * from RepairsStatus where RepairID = @0", RepairID);
                        foreach (var status in statuses)
                        {
                            db.Delete(status);
                        }
                        scope.Complete();


                    }
                    return Json(new { Result = "OK" });
                }
            }
            catch (Exception ex)
            {

                _log.Error(ex);
                return Json(new { Result = "ERROR", Message = _message });
            }
        }
        [HttpPost]
        public JsonResult UpdateRepair(Repair repair)
        {
            try
            {
                using (var db = new Database("DefaultConnection"))
                {

                    db.Update(repair);

                }
                return Json(new { Result = "OK" });
            }


            catch (Exception ex)
            {
                _log.Error(ex);
                return Json(new { Result = "ERROR", Message = _message });
            }
        }
        /// <summary>
        /// Get Repair for Employee
        /// </summary>
        /// <param name="customerID"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetRepairForEmployeeById(string employeeID)
        {
            try
            {
                using (var db = new Database("DefaultConnection"))
                {
                    var result = db.Fetch<Repair>("Select * from dbo.Repairs where EmployeeID = @0", employeeID);
                    return Json(new { Result = "OK", Records = result });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

Portal/MiniCrm.Web/Views/Shared/_Layout.cshtml
@using System.Web
<!DOCTYPE html>
<html>
<head>
    <style>
        td.details-control {
            background: url('../resources/details_open.png') no-repeat center center;
            cursor: pointer;
        }

        tr.shown td.details-control {
            background: url('../resources/details_close.png') no-repeat center center;
        }
    </style>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="@Url.Content("/Scripts/jquery-2.1.3.js")"></script>
    <title>@ViewBag.Title - Inter-Warsztat</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("JavaScript", required: false)
</head>
<body style="padding: 0">
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inter-Warsztat", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("O nas", "About", "Home")</li>
                    <li>@Html.ActionLink("Oferta", "OfferList", "Offer")</li>

                    @if (Request.IsAuthenticated)
                    {
                        if (Context.User.IsInRole("admin"))
                        {
                            if (Context.User.IsInRole("admin"))
                            {
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mailing <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Pokaż wysłane e-maile", "Mailing", "Mailing")</li>


                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Naprawy <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Zarządzaj", "Repair", "Repair")</li>
                                    </ul>
                                </li>


                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Klient<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Dodaj klienta", "RegisterCustomer", "Account")</li>
                                        <li>@Html.ActionLink("Zarządzaj", "Customer", "Customer")</li>
                                    </ul>
                                </li>
                            }


                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pracownik<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Dodaj pracownika", "RegisterEmployee", "Account")</li>
                                    <li>@Html.ActionLink("Zarządzaj", "Employee", "Employee")</li>
                                </ul>
                            </li>
                        }

                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="body-content container">
        @RenderBody()
    </div>
    <div style="padding-top: 30px">
        <footer div class="navbar-fixed-bottom" style="font-size: 11px; margin-top: 100%; font-weight: 200; line-height: 2.1428571435; color: inherit; background-color: #eeeeee;">
            <div style="text-align:right">
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseFooter" aria-expanded="false" aria-controls="collapseFooter">
                    CopyRights
                </button>
            </div>
            <div class="collapse" id="collapseFooter">
                <div class="well">
                    <p>Copyright ©2015, All Rights Reserved @DateTime.Now.Year - Enzo IT Sollution - Chodkiewicz & Ostrowski</p>
                    <p>"Z nami niepewność zaczyna się wczoraj..."</p>
                </div>
            </div>

        </footer>
    </div>


    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

Portal/MiniCrm.Web/Views/Shared/_LayoutClientPanel.cshtml
<!DOCTYPE html>

<html>
<head>
 
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="@Url.Content("/Scripts/jquery-2.1.3.js")"></script>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("JavaScript", required: false)
</head>
<body style="padding:0">
    <div class="navbar navbar-inverse navbar-static-top" style="padding-top: 0p">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-toggle"></span>
                </button>
                @Html.ActionLink("Inter-Warsztat", "Index", "ClientPanel", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @Html.Partial("_LoginPartial")

                </ul>
            </div>
        </div>
    </div>

    <div class="container">

        <div class="row">
            <div class="col-sm-3">

                <h3><i class="glyphicon glyphicon-briefcase"></i> Panel</h3>


                <ul class="nav nav-stacked">
                    <li> @Html.ActionLink(" Moje Pojazdy", "MyVehicles", "ClientPanel")</li>
                    <li> @Html.ActionLink(" Naprawy", "MyRepair", "ClientPanel")</li>
                    <li>@Html.ActionLink("Statusy Napraw", "MyStatusRapair", "ClientPanel")</li>
                    <li>@Html.ActionLink("Zgody Napraw", "MyPermission", "ClientPanel")</li>
      
                </ul>


            </div>
            <div class="col-sm-8">


                <div class="row">



                    <div class="body-content container">
                        @RenderBody()
                    </div>


                </div>
            </div>
        </div>

    </div>
    <div style="padding-top: 10px">
        <footer div class="navbar-fixed-bottom" style="font-size: 11px; margin-top: 100%; font-weight: 200; line-height: 2.1428571435; color: inherit; background-color: #eeeeee;">
            <div style="text-align:right">
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseFooter" aria-expanded="false" aria-controls="collapseFooter">
                    CopyRights
                </button>
            </div>
            <div class="collapse" id="collapseFooter">
                <div class="well">
                    <p>Copyright ©2015, All Rights Reserved @DateTime.Now.Year - Enzo IT Sollution - Chodkiewicz & Ostrowski</p>
                    <p>"Z nami niepewność zaczyna się wczoraj..."</p>
                </div>
            </div>

        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>


</html>